### ISSUE TITLE
trouble loading policy, kube-mgmt logs throwing error

### ISSUE THREAD

**Issue by DarthVader2409** [open-policy-agent/kube-mgmt#63]
I am trying to roll out opa with helm chart. The chart was successfully rolled out but now I am having trouble enforcing the policy.

**Version of Kubernetes**:
k8s- v1.15.6
opa- opa:0.15.1
kube-mgmt- 0.10

**What happened**:
my config map looks like this
```
Name:         admission-control
Namespace:    opa-test
Labels:       openpolicyagent.org/policy=rego
Annotations:  openpolicyagent.org/policy-status: {"status":"ok"}

Data
====
admission-policy.rego:
----
package kubernetes.admission

deny[reason] {
  some container
  input_containers[container]
  not startswith(container.image, "docker-integration.cernerrepos.net")
  reason := "container image refers to wrong registry, must be from docker-integration.cernerrepos.net"
}

input_containers[container] {
  container := input.request.object.spec.containers[_]
}

input_containers[container] {
  container := input.request.object.spec.template.spec.containers[_]
}

Events:  <none>

``` 

```
      - name: mgmt
          image: openpolicyagent/kube-mgmt:0.10
          imagePullPolicy: IfNotPresent
          resources:
            {}
            
          args:
            - --opa-auth-token-file=/bootstrap/mgmt-token
            - --opa-url=http://127.0.0.1:8181/v1
            - --replicate-path=kubernetes
            - --enable-data=false
            - --enable-policies=true
            - --policies=opa-test
            - --require-policy-label=true
```

I went ahead and looked up my kube-mgmt logs and it shows-
```
time="2020-01-27T22:55:11Z" level=warning msg="First line of log stream."
E0127 23:03:12.799556       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Status" is registered for version "v1" in scheme "github.com/open-policy-agent/kube-mgmt/pkg/configmap/configmap.go:102"
E0127 23:04:53.804350       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Status" is registered for version "v1" in scheme "github.com/open-policy-agent/kube-mgmt/pkg/configmap/configmap.go:102"
```

**What you expected to happen**:

Expected the policy to be enforced

I am not sure of this logs I am seeing here in kube-mgmt.

**Comment by ashutosh-narkar** [comment]
`openpolicyagent/kube-mgmt:0.11` should solve the `no kind "Status" is registered` issue. Here's the original issue https://github.com/open-policy-agent/kube-mgmt/issues/49. 

I would recommend unit testing the polices prior to use https://www.openpolicyagent.org/docs/latest/policy-testing/

**Comment by DarthVader2409** [comment]
Thanks @ashutosh-narkar ! Using openpolicyagent/kube-mgmt:0.11 fixed that issue. 
But my policy is still not enforced even though it is getting annotated.
There are no error logs in kube-mgmt and opa containers. 
I have tested my policy [here](https://play.openpolicyagent.org/) and it works fine (It is the standard policy of image being pulled from a specific registry). Here is my config map 
```
Name:         admission-control
Namespace:    opa-test
Labels:       openpolicyagent.org/policy=rego
Annotations:  openpolicyagent.org/policy-status: {"status":"ok"}

Data
====
admission-policy.rego:
----
package kubernetes.admission

deny[reason] {
  some container
  input_containers[container]
  not startswith(container.image, "docker-secure.xyz.net")
  reason := "container image refers to wrong registry, must be from docker-secure.xyz.net"
}

input_containers[container] {
  container := input.request.object.spec.containers[_]
}

input_containers[container] {
  container := input.request.object.spec.template.spec.containers[_]
}

Events:  <none>
```
Would appreciate the suggestions you have regarding this.

**Comment by ashutosh-narkar** [comment]
Can you share your OPA logs ? Do you see any `POST` requests in the logs ? Also sharing your manifest would help.

**Comment by DarthVader2409** [comment]
Yup I can see post requests in my opa logs.
Here is a gist of my opa logs https://gist.github.cerner.com/ar071755/22aa595d324ffa69298642e34ba46f68

Here is the generated manifest- 
https://gist.github.cerner.com/ar071755/545a041e20eb51e5fd4acd345a038dda

**Comment by DarthVader2409** [comment]
Yes I can see POST request in my OPA logs
Manifest file https://gist.github.com/DarthVader2409/fbf1f7a10ce3f560d8f4268edc57d1a0
OPA logs https://gist.github.com/DarthVader2409/4b07c9b455aaa0a3bd9e1ac678244045

**Comment by ashutosh-narkar** [comment]
Can you set the log level to `debug` https://gist.github.com/DarthVader2409/fbf1f7a10ce3f560d8f4268edc57d1a0#file-helm_opa-L197

**Comment by DarthVader2409** [comment]
https://gist.github.com/DarthVader2409/7ad1b049686d9f9410e4b522319b7f71

**Comment by ashutosh-narkar** [comment]
I don't see any create request for a resource like pods in the logs. What requests are you executing ?

**Comment by DarthVader2409** [comment]
I am doing a 
`kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml -n myspace`
But policy is not stoping deployment from pulling images from that registry and the deployment is getting created.

**Comment by DarthVader2409** [comment]
```
[INFO] Received request.
  client_addr = "172.16.0.0:41462"
  req_id = 10577
  req_method = "POST"
  req_path = "/"
  req_body = |
      {"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1beta1","request":{"uid":"f2525062-00fa-4fef-86ee-cbfa094591fe","kind":{"group":"authorization.k8s.io","version":"v1beta1","kind":"SubjectAccessReview"},"resource":{"group":"authorization.k8s.io","version":"v1beta1","resource":"subjectaccessreviews"},"requestKind":{"group":"authorization.k8s.io","version":"v1beta1","kind":"SubjectAccessReview"},"requestResource":{"group":"authorization.k8s.io","version":"v1beta1","resource":"subjectaccessreviews"},"operation":"CREATE","userInfo":{"username":"system:node:worker-k8s-corp-opsdev-0-ls5ipesxs3-az3-10-190-168-192","groups":["system:nodes","system:authenticated"]},"object":{"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"verb":"get","version":"v1","resource":"nodes","subresource":"proxy","name":"worker-k8s-corp-opsdev-0-ls5ipesxs3-az3-10-190-168-192"},"user":"kube-apiserver-kubelet-client","group":["system:masters","system:authenticated"]},"status":{"allowed":false}},"oldObject":null,"dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1"}}}


  req_params = |
      {
        "timeout": [
          "30s"
        ]
      }

[INFO] Sent response.
  resp_bytes = 94
  resp_duration = 2.222902
  resp_body = |
      {
        "apiVersion": "admission.k8s.io/v1beta1",
        "kind": "AdmissionReview",
        "response": {
          "allowed": true
        }
      }
  client_addr = "172.16.0.0:41462"
  req_id = 10577
  req_method = "POST"
  req_path = "/"
  resp_status = 200
```

**Comment by ashutosh-narkar** [comment]
1) I would have expected to see a deployment creation event in the OPA logs when the `kubectl` command is executed.

2) Apart from the Config Map you posted as there any other Config Maps that contain policy ?

**Comment by DarthVader2409** [comment]
1. That is right. If OPA logs could see the event then it would have executed the policy, but in this case OPA is unable to intercept that event somehow.

2. This is the only config map that contains policy.

**Comment by ashutosh-narkar** [comment]
By default, when a POST is made to `/`, OPA will query the document at `data.system.main` for a decision unless the `default_decision` parameter is set in the OPA config.  ```"response": {
          "allowed": true
        }``` looks like OPA is querying something to get a decision.  Hence I asked if there is some other policy loaded somewhere.

Also check the Kube api server logs for any relevant logs.

**Comment by DarthVader2409** [comment]
```
{"log":"I0130 17:15:55.390687       1 controller.go:127] OpenAPI AggregationController: action for item v1beta1.webhook.certmanager.k8s.io: Rate Limited Requeue.\n","stream":"stderr","time":"2020-01-30T17:15:55.3908546Z"}
{"log":"E0130 17:15:59.796212       1 oidc.go:232] oidc authenticator: initializing plugin: Get https://dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net/.well-known/openid-configuration: x509: certificate is not valid for any names, but wanted to match dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net\n","stream":"stderr","time":"2020-01-30T17:15:59.796386021Z"}
{"log":"E0130 17:16:09.795107       1 oidc.go:232] oidc authenticator: initializing plugin: Get https://dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net/.well-known/openid-configuration: x509: certificate is not valid for any names, but wanted to match dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net\n","stream":"stderr","time":"2020-01-30T17:16:09.795251121Z"}
{"log":"E0130 17:16:19.798747       1 oidc.go:232] oidc authenticator: initializing plugin: Get https://dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net/.well-known/openid-configuration: x509: certificate is not valid for any names, but wanted to match dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net\n","stream":"stderr","time":"2020-01-30T17:16:19.798934131Z"}
{"log":"E0130 17:16:29.797140       1 oidc.go:232] oidc authenticator: initializing plugin: Get https://dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net/.well-known/openid-configuration: x509: certificate is not valid for any names, but wanted to match dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net\n","stream":"stderr","time":"2020-01-30T17:16:29.797281588Z"}
{"log":"E0130 17:16:39.798250       1 oidc.go:232] oidc authenticator: initializing plugin: Get https://dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net/.well-known/openid-configuration: x509: certificate is not valid for any names, but wanted to match dex.vsphere-ls-k8s-corp-opsdev-0.northamerica.cerner.net\n","stream":"stderr","time":"2020-01-30T17:16:39.798425454Z"}
{"log":"I0130 17:16:41.519796       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io\n","stream":"stderr","time":"2020-01-30T17:16:41.519962965Z"}
root@master-k8s-corp-opsdev-0-ls5ipesxs3-az3-10-190-168-12:/var/log/containers ( node_name         'chef-zero' )
17:16:49 #
```

kube api server logs looks normal.
I was wondering that I am generating the manifest using helm chart and my values.yaml file contains this section: 
```
opa:
  services:
    controller:
      url: 'https://www.openpolicyagent.org'
  bundles:
    quickstart:
      service: controller
      resource: /bundles/helm-kubernetes-quickstart
  default_decision: /helm_kubernetes_quickstart/main

```
Would it be because of bundle declared here it is making these "allow" response to query. From my testing I have seen that if I remove this block my POST requests results in 404 error as it won't find the document in data.system.main

**Comment by ashutosh-narkar** [comment]
You can examine the policy in that bundle by doing:

```bash
mkdir example && cd example
curl -s -L https://www.openpolicyagent.org/bundles/kubernetes/admission | tar xzv
```

Check if that's allowing your requests to go through.

**Comment by DarthVader2409** [comment]
I examined that bundle, it just has ingress_whitelist policy but  that policy is also not getting executed, I verified that. 

I followed the opa getting started tutorial and it was a cake walk to get my policy enforced. But generating manifest using helm is the issue. I think something is up with public helm chart stable/opa. Have you ever tried to generate manifest using that?

**Comment by ashutosh-narkar** [comment]
I haven't tried the helm chart. I assume you are following [this](https://github.com/helm/charts/tree/master/stable/opa). 

Also the config map policies are disabled by default https://github.com/helm/charts/blob/master/stable/opa/values.yaml#L126.

**Comment by DarthVader2409** [comment]
Yes this is what I am following. I have enabled the config map policies, added rules to rbac and also included the label in my policy configmap.

**Comment by ashutosh-narkar** [comment]
From the OPA debug logs you sent, I would have expected to see some logs corresponding to the below command you executed:
```kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml -n myspace```

When you run the above command, do you see any OPA logs ?

**Comment by DarthVader2409** [comment]
```
[INFO] Received request.
  req_body = |
      {"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1beta1","request":{"uid":"b477ae19-eb36-4210-812c-c7400efb444b","kind":{"group":"","version":"v1","kind":"Event"},"resource":{"group":"","version":"v1","resource":"events"},"requestKind":{"group":"","version":"v1","kind":"Event"},"requestResource":{"group":"","version":"v1","resource":"events"},"namespace":"norbert","operation":"CREATE","userInfo":{"username":"system:node:worker-k8s-corp-opsdev-0-ls5ipesxs3-az2-10-190-168-160","groups":["system:nodes","system:authenticated"]},"object":{"kind":"Event","apiVersion":"v1","metadata":{"name":"nginx-deployment-7c4d86bc68-6lrsg.15eed3c61073d45a","namespace":"norbert","uid":"946527e8-1f46-42b2-bb1e-533a674987b9","creationTimestamp":"2020-01-31T01:16:06Z"},"involvedObject":{"kind":"Pod","namespace":"norbert","name":"nginx-deployment-7c4d86bc68-6lrsg","uid":"4cf29190-37ea-4eee-aa14-285fd355b9ee","apiVersion":"v1","resourceVersion":"177204886","fieldPath":"spec.containers{nginx}"},"reason":"Started","message":"Started container nginx","source":{"component":"kubelet","host":"worker-k8s-corp-opsdev-0-ls5ipesxs3-az2-10-190-168-160"},"firstTimestamp":"2020-01-31T01:16:06Z","lastTimestamp":"2020-01-31T01:16:06Z","count":1,"type":"Normal","eventTime":null,"reportingComponent":"","reportingInstance":""},"oldObject":null,"dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1"}}}


  req_params = |
      {
        "timeout": [
          "30s"
        ]
      }
  client_addr = "172.16.5.0:52176"
  req_id = 75464
  req_method = "POST"
  req_path = "/"

[INFO] Sent response.
  req_method = "POST"
  req_path = "/"
  resp_status = 200
  resp_bytes = 94
  resp_duration = 3.735764
  resp_body = |
      {
        "apiVersion": "admission.k8s.io/v1beta1",
        "kind": "AdmissionReview",
        "response": {
          "allowed": true
        }
      }
  client_addr = "172.16.5.0:52176"
  req_id = 75464
```

**Comment by ashutosh-narkar** [comment]
I would have expected more of a deployment/pod etc. creation log. I noticed your manifest is different from the stable helm chart.  Have you been able to get that working as is ? Also there could possibly been an issue with the helm chart as well.

**Comment by DarthVader2409** [comment]
I am a part of Managed Kubernetes team and we manage a large number of clusters. we have enabled some Pod Security Policies, so to get the helm chart to working I had to add those psp's and that is the only other thing I have added to the helm chart to get that working. I had to do the same for getting the OPA tutorial to work too.

**Comment by ashutosh-narkar** [comment]
Ok. The OPA response ```"response": {
          "allowed": true
        }``` makes sense as OPA is not getting the event you expect to be denied. What would be the best way to reproduce what your doing ? What's in https://k8s.io/examples/controllers/nginx-deployment.yaml ?

**Comment by ashutosh-narkar** [comment]
What's the best way to reproduce what you are doing ?

**Comment by ashutosh-narkar** [comment]
This is the input OPA gets from what you've posted. Notice the container has already started.  
```json
{
       "kind": "AdmissionReview",
       "apiVersion":"admission.k8s.io/v1beta1",
       "request": {
         "uid":"b477ae19-eb36-4210-812c-c7400efb444b",
         "kind":{"group":"","version":"v1","kind":"Event"},
         "resource":{"group":"","version":"v1","resource":"events"},
         "requestKind":{"group":"","version":"v1","kind":"Event"},
         "requestResource":{"group":"","version":"v1","resource":"events"},
         "namespace":"norbert",
         "operation":"CREATE",
         "userInfo": {
              "username":"system:node:worker-k8s-corp-opsdev-0-ls5ipesxs3-az2-10-190-168-160",
              "groups":["system:nodes","system:authenticated"]
          },
          "object": {
              "kind":"Event",
              "apiVersion":"v1",
              "metadata": {
                 "name":"nginx-deployment-7c4d86bc68-6lrsg.15eed3c61073d45a",
                 "namespace":"norbert",
                 "uid":"946527e8-1f46-42b2-bb1e-533a674987b9",
                 "creationTimestamp":"2020-01-31T01:16:06Z"},
                 "involvedObject": {
                          "kind":"Pod",
                          "namespace":"norbert",
                          "name":"nginx-deployment-7c4d86bc68-6lrsg",
                          "uid":"4cf29190-37ea-4eee-aa14-285fd355b9ee",
                          "apiVersion":"v1",
                          "resourceVersion":"177204886",
                          "fieldPath":"spec.containers{nginx}"
                  },
                  "reason":"Started",
                  "message":"Started container nginx",
                  "source":{"component":"kubelet",
                            "host":"worker-k8s-corp-opsdev-0-ls5ipesxs3-az2-10-190-168-160"},
                            "firstTimestamp":"2020-01-31T01:16:06Z",
                            "lastTimestamp":"2020-01-31T01:16:06Z",
                            "count":1,"type":"Normal","eventTime":null,
                            "reportingComponent":"","reportingInstance":""
                  },
                  "oldObject":null,
                  "dryRun":false,"options":{"kind":"CreateOptions","apiVersion":"meta.k8s.io/v1"
              }
            }
          }
```

Typically I would expect an input like:

```json
apiVersion: admission.k8s.io/v1beta1
kind: AdmissionReview
request:
  kind:
    group: extensions
    kind: Ingress
    version: v1beta1
  operation: CREATE
  userInfo:
    groups:
    username: alice
  object:
    metadata:
      name: prod
    spec:
      rules:
      - host: initech.com
        http:
          paths:
          - path: /finance
            backend:
              serviceName: banking
```

**Comment by DarthVader2409** [comment]
I see what you are looking for, let me dig in my log. Meanwhile interesting thing is that, I just queried OPA to see the policy it is loading , turns out it is loading the policy from that bundle we discussed earlier which has ingress whitelist policy and yesterday I applied an ingress_bad.yaml file and that went through without any restrictions. 


**Steps to reproduce:**
1. Clone https://github.com/helm/charts/tree/master/stable/opa
2. Create a namespace "opa-test"
3. Enable the config map section in public helm like we discussed above
4. [This](https://gist.github.com/DarthVader2409/678f3d53b97aeded326d3ec933535d85) is how my values.yaml looks like.
5. Generate a manifest (I am using helm to generate one) and apply that.
6. Create a config map for any policy.
7. Test that the policy is enforced.

**Comment by DarthVader2409** [comment]
tbh I am not quiet able to make sense of [this](https://gist.github.com/DarthVader2409/327314cf10e22a67f989365c80e3ba5b) log.

I can see `"req_path": "/v1/policies/opa-test/admission-control/admission-policy.rego"` in some logs. and my deny message as well. But even then the deployment is getting created later.

**Comment by DarthVader2409** [comment]
Here are the logs for create, pulled image and start container https://gist.github.com/DarthVader2409/c38a7fd2da82023a66a845a6a613bc6f

**Comment by DarthVader2409** [comment]
I took a closer look on my query to OPA for inspecting all the loaded policy. Turns out my policy is . also up there. 
```
➜  ~ curl -k -s https://localhost:8080/v1/policies | jq -r '.result[].raw'
package test_helm_kubernetes_quickstart

import data.helm_kubernetes_quickstart

test_allow_outside_example_namespace {
    helm_kubernetes_quickstart.deny == set() with input as {
        "request": {
            "operation": "CREATE",
            "kind": {"kind": "Ingress"},
            "namespace": "default",
            "object": {
                "spec": {
                    "rules": [
                        {
                            "host": "payments.acmecorp.com",
                        },
                    ]
                }
            }
        }
    }
}

test_allow_inside_example_namespace {
    helm_kubernetes_quickstart.deny == set() with input as {
        "request": {
            "operation": "CREATE",
            "kind": {"kind": "Ingress"},
            "namespace": "opa-example",
            "object": {
                "spec": {
                    "rules": [
                        {
                            "host": "payments.dev.acmecorp.com",
                        },
                    ]
                }
            }
        }
    }
    helm_kubernetes_quickstart.deny == set() with input as {
        "request": {
            "operation": "CREATE",
            "kind": {"kind": "Ingress"},
            "namespace": "opa-example",
            "object": {
                "spec": {
                    "rules": [
                        {
                            "host": "payments.test.acmecorp.com",
                        },
                    ]
                }
            }
        }
    }
}

test_deny_inside_example_namespace {
    helm_kubernetes_quickstart.deny["ingress host \"payments.acmecorp.com\" is invalid"] with input as {
        "request": {
            "operation": "CREATE",
            "kind": {"kind": "Ingress"},
            "namespace": "opa-example",
            "object": {
                "spec": {
                    "rules": [
                        {
                            "host": "payments.acmecorp.com",
                        },
                    ]
                }
            }
        }
    }
}
package kubernetes.admission

deny[reason] {
  some container
  input_containers[container]
  not startswith(container.image, "docker-secure.cernerrepos.net")
  reason := "container image refers to wrong registry, must be from docker-secure.cernerrepos.net"
}

input_containers[container] {
  container := input.request.object.spec.containers[_]
}

input_containers[container] {
  container := input.request.object.spec.template.spec.containers[_]
}

package kubernetes.admission

deny[reason] {
  some container
  input_containers[container]
  not startswith(container.image, "docker-secure.cernerrepos.net")
  reason := "container image refers to wrong registry, must be from docker-secure.cernerrepos.net"
}

input_containers[container] {
  container := input.request.object.spec.containers[_]
}

input_containers[container] {
  container := input.request.object.spec.template.spec.containers[_]
}

package helm_kubernetes_quickstart

whitelist = [
	"*.dev.acmecorp.com",
	"*.test.acmecorp.com",
]

deny[msg] {
	input.request.kind.kind == "Ingress"
	input.request.operation == "CREATE"
	input.request.namespace == "opa-example"
	host := input.request.object.spec.rules[_].host
	not glob_match_one_of(whitelist, host)
	msg := sprintf("ingress host %q is invalid", [host])
}

glob_match_one_of(patterns, str) {
	glob.match(patterns[_], ["."], str)
}

main = {
	"apiVersion": "admission.k8s.io/v1beta1",
	"kind": "AdmissionReview",
	"response": response,
}

default response = {"allowed": true}

response = {
	"allowed": false,
	"status": {"reason": reason},
} {
	reason := concat(", ", deny)
	reason != ""
}
```

**Comment by DarthVader2409** [comment]
This might be the reson it shows up in the log. But I have no answer for the reason it is not getting enforced.

**Comment by ashutosh-narkar** [comment]
I'll have to try this out. Could be an issue with the chart too.

**Comment by DarthVader2409** [comment]
Thanks Ashutosh for taking out time to look into this! Appreciate your help. I really like the OPA concept, having a reliable helm support for this would make it easy to roll out and keeping up with all latest images and stuff.

**Comment by ashutosh-narkar** [comment]
Your [values.yaml](https://gist.github.com/DarthVader2409/678f3d53b97aeded326d3ec933535d85#file-values-yaml-L8-L16) just like the default one is using bundles. That bundle owns the root `kubernetes.admission`. So when you try to load your policy with that same root, the bundle will overwrite it and hence your policy won't get enforced. More info on this can be found [here](https://www.openpolicyagent.org/docs/latest/management/#multiple-sources-of-policy-and-data).

The quickest way to enforce your policy would be to comment out [this](https://gist.github.com/DarthVader2409/678f3d53b97aeded326d3ec933535d85#file-values-yaml-L9-L16) section from the values.yaml.

Then load a `main.rego` followed by your own policy. 

**main.rego**
```rego
package system

import data.kubernetes.admission

main = {
        "apiVersion": "admission.k8s.io/v1beta1",
        "kind": "AdmissionReview",
        "response": response,
}

default response = {"allowed": true}

response = {
        "allowed": false,
        "status": {"reason": reason},
} {
        reason := concat(", ", admission.deny)
        reason != ""
}
```

```bash
kubectl create configmap main --from-file=main.rego -n opa
kubectl label configmap -n opa main openpolicyagent.org/policy=rego
```
**admission-policy.rego** (*updated_your_policy*)
```rego
package kubernetes.admission

operations = {"CREATE", "UPDATE"}

deny[reason] {
  input.request.kind.kind == "Deployment"
  operations[input.request.operation]
  container := input_containers[_]
  not startswith(container.image, "docker-integration.cernerrepos.net")
  reason := sprintf("container '%s' image refers to wrong registry, must be from docker-integration.cernerrepos.net", [container.name])
}

input_containers[c] {
  c := input.request.object.spec.containers[_]
}

input_containers[c] {
  c := input.request.object.spec.template.spec.containers[_]
}
```

```bash
kubectl create configmap ingress-whitelist --from-file=admission-policy.rego -n opa
kubectl label configmap -n opa ingress-whitelist openpolicyagent.org/policy=rego
```

After the policies have loaded successfully, try your deployment command. It should get blocked.

**Comment by ashutosh-narkar** [comment]
In the long run, you would want to load your own polices using bundles.

**Comment by DarthVader2409** [comment]
Ah, that bundle part was really confusing and throwing me out. I tried to remove it but then I was getting a 404 because I was missing main.rego config map. Got it now. Thank you for all your help and time. Really appreciate it!!! This is not very intuitive for a new user, I have seen some other people posting similar questions on their github. So I will make p/r to upadate the helm opa readme with this information.
